export default {
  START_FETCH_LIST: 'START_FETCH_LIST',
  FETCH_LIST_SUCCESS: 'FETCH_LIST_SUCCESS',
  FETCH_LIST_FAILED: 'FETCH_LIST_FAILED',

  START_FETCH_TAGS: 'START_FETCH_TAGS',
  FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
  FETCH_TAGS_FAILED: 'FETCH_TAGS_FAILED',

  START_VERIFY_TOKEN: 'START_VERIFY_TOKEN',
  VERIFY_TOKEN_SUCCESS: 'VERIFY_TOKEN_SUCCESS',
  VERIFY_TOKEN_FAILED: 'VERIFY_TOKEN_FAILED',

  START_VERIFY_LOGIN: 'START_VERIFY_LOGIN',
  VERIFY_LOGIN_SUCCESS: 'VERIFY_LOGIN_SUCCESS',
  VERIFY_LOGIN_FAILED: 'VERIFY_LOGIN_FAILED',

  START_REMOVE_TOKEN: 'START_REMOVE_TOKEN',
  REMOVE_TOKEN_SUCCESS: 'REMOVE_TOKEN_SUCCESS',

  SET_ERROR_MSG: 'SET_ERROR_MSG',
  RESET_ERROR_MSG: 'RESET_ERROR_MSG',

  START_ADD_POST: 'START_ADD_POST',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FAILED: 'ADD_POST_FAILED',
}
