export default {
  START_FETCH_LIST: 'START_FETCH_LIST',
  FETCH_LIST_SUCCESS: 'FETCH_LIST_SUCCESS',
  FETCH_LIST_FAILED: 'FETCH_LIST_FAILED',
  START_FETCH_TAGS: 'START_FETCH_TAGS',
  FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
  FETCH_TAGS_FAILED: 'FETCH_TAGS_FAILED'
}
